### PR TITLE
rating fix

### PR DESCRIPTION
**Pull request by Spoonge**
i forgot to remove the space before getdoublefromtext

### CODE REVIEW

**Comment by ImZaw** [comment]
The issue isnt spacing or anything else but, the rating does not exist somehow and it keeps failing in the builds

**Comment by ImZaw** [comment]
[build: StablePlugin/src/main/kotlin/com/stable/Movizland.kt#L53](https://github.com/ImZaw/Arabic-Plugins/commit/9715d9015d73b6c626fd21e9e58958765a6f63bf#annotation_4275488127)
Cannot find a parameter with this name: rating

**Comment by Spoonge** [comment]
i've used sunstream for building thats why i had no errors

**Comment by ImZaw** [comment]
> i've used sunstream for building thats why i had no errors

Yeah makes sense

**Pull request closed without merging**
